/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package brutelol.items.abstracts;

/**
 *
 * @author Talonos
 */
public enum CPassive 
{
    RAGE_PASSIVE, 
    BLOODTHIRSTER_PASSIVE, 
    FROZEN_MALLET_PASSIVE,
    HYDRA_PASSIVE, 
    MALMORTIUS_PASSIVE, 
    RUINED_KING_PASSIVE,    //Accounted for in AbstractCharacter'sBonus Physical Damage
    ESSENCE_REAVER_PASSIVE,
    BLACK_CLEAVER_PASSIVE, 
    RANDUINS_OMEN_PASSIVE, 
    NASHOR_PASSIVE,
    RYLAIS_PASSIVE,
    LIANDRYS_PASSIVE,
    TENACITY_PASSIVE,
    PHANTOM_DANCER_PASSIVE,
    VALORS_REWARD_PASSIVE, 
    SPIRIT_VISAGE_PASSIVE,
    BANSHEES_VEIL_PASSIVE, 
    GUARDIAN_ANGEL_PASSIVE, 
    
    MERCURIAL_SCIMITAR_ACTIVE, 
    STATIS_ACTIVE, 
    HEXTECH_GUNBLADE_ACTIVE,
    DEATHFIRE_ACTIVE, 
    QUICKSILVER_ACTIVE,
    LOCKET_ACTIVE,
    
    ROD_OF_AGES_GROWTH, 
    MANA_CHARGE_STAFF_GROWTH, 
    MANA_CHARGE_SWORD_GROWTH, 
    MANA_CHARGE_TEAR_GROWTH, 
    
    SERAPHS_ACTIVE, YOUMUUS_GHOSTBLADE_ACTIVE, ENTROPY_ACTIVE, BLACKFIRE_TORCH_ACTIVE, SUNFIRE_CAPE_PASSIVE, FROZEN_HEART_PASSIVE, ATHENES_UNHOLY_GRAIL_PASSIVE, GUINSOOS_RAGEBLADE_PASSIVE, GUINSOOS_RAGEBLADE_UNIQUE_PASSIVE, 
}
